# Generated by Django 3.2.16 on 2022-12-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('mangmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Bandeau'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Bandeau'),
        ),
        migrations.AlterField(
            model_name='structuresettings',
            name='plateformUrl',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien de la plateforme'),
        ),
    ]
