# Generated by Django 3.2.16 on 2022-12-06 15:44

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mangmap', '0002_auto_20221201_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='newsletter_text',
        ),
        migrations.RemoveField(
            model_name='site',
            name='is_global',
        ),
        migrations.AddField(
            model_name='sitespage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='sitespage',
            name='list_displayed',
            field=models.BooleanField(default=True, verbose_name='Affichage de la version en liste'),
        ),
    ]
