# Generated by Django 3.2.16 on 2022-12-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangmap', '0004_auto_20221206_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_block_cta',
            field=models.CharField(blank=True, default='Accéde au formulaire', max_length=32, verbose_name='Text du bouton'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_block_description',
            field=models.CharField(blank=True, max_length=256, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_block_title',
            field=models.CharField(blank=True, default='Conactez-nous', max_length=64, verbose_name='Titre'),
        ),
    ]
