# Generated by Django 3.2.16 on 2022-12-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangmap', '0005_auto_20221206_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='news',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='news',
            name='thematics',
        ),
        migrations.RemoveField(
            model_name='news',
            name='types',
        ),
        migrations.RemoveField(
            model_name='news',
            name='zones',
        ),
        migrations.RemoveField(
            model_name='site',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='site',
            name='main_thematic',
        ),
        migrations.RemoveField(
            model_name='site',
            name='thematics',
        ),
        migrations.RemoveField(
            model_name='site',
            name='types',
        ),
        migrations.RemoveField(
            model_name='site',
            name='zones',
        ),
        migrations.RemoveField(
            model_name='thematic',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='worldzone',
            name='icon',
        ),
        migrations.DeleteModel(
            name='ActualityType',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='SiteType',
        ),
        migrations.DeleteModel(
            name='Thematic',
        ),
        migrations.DeleteModel(
            name='WorldZone',
        ),
    ]
