# Generated by Django 3.2.16 on 2022-12-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangmap', '0007_auto_20221208_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualitytype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='actualitytype',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, verbose_name="Slug (URL de l'actualité)"),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, verbose_name='Slug (URL du site)'),
        ),
        migrations.AlterField(
            model_name='sitetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='sitetype',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='thematic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='thematic',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, verbose_name='Slug'),
        ),
    ]
