# Generated by Django 3.2.16 on 2022-12-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangmap', '0008_auto_20221208_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='geo_dev_creation',
        ),
        migrations.RemoveField(
            model_name='site',
            name='source_name',
        ),
        migrations.AddField(
            model_name='site',
            name='tiles_nb',
            field=models.IntegerField(default=0, verbose_name='Nombre de tuiles'),
        ),
        migrations.AlterField(
            model_name='actualitytype',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='sitetype',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='thematic',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, verbose_name='Slug'),
        ),
    ]
