# Generated by Django 3.2.16 on 2022-12-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangmap', '0009_auto_20221208_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='coastline_coverage',
            field=models.IntegerField(default=0, verbose_name='Pourcentage de couverture du littoral'),
        ),
    ]
