# Generated by Django 3.2.16 on 2022-12-08 17:18

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mangmap', '0010_site_coastline_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='key_figures_introduction',
            field=wagtail.fields.RichTextField(default='Quelques chiffres clés', verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='key_figures_sites_nb_title',
            field=models.CharField(blank=True, default='Nombre de sites', max_length=64, verbose_name='Titre pour le nombre de site mangroves'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='key_figures_tiles_nb_title',
            field=models.CharField(blank=True, default='Nombre de tuiles', max_length=64, verbose_name='Titre pour le nombre de tuiles'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='key_figures_year',
            field=models.CharField(blank=True, default='Années disponibles', max_length=64, verbose_name='Titre pour les années disponibles'),
        ),
    ]
