# Generated by Django 3.2.16 on 2022-12-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangmap', '0011_auto_20221208_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='show_in_footer',
            field=models.BooleanField(default=False, help_text='Si un lien vers cette page devra apparaître dans le bas de page', verbose_name='Faire apparaître dans le bas de page'),
        ),
        migrations.AlterField(
            model_name='site',
            name='coastline_coverage',
            field=models.CharField(blank=True, max_length=8, verbose_name='Couverture du littoral'),
        ),
        migrations.DeleteModel(
            name='NewsLetterSettings',
        ),
    ]
