# Generated by Django 3.2.16 on 2022-12-19 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangmap', '0015_auto_20221215_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='introduction_youtube_video_id',
            field=models.CharField(blank=True, help_text="Indiquer ici seulement l'id de la video youtube, celui-ci est indiqué dans l'url après 'v='. Exemple : pour https://www.youtube.com/watch?v=r3pQdvIHYBE renseigner r3pQdvIHYBE", max_length=15, null=True, verbose_name='Vidéo Youtube (id)'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='show_in_footer',
            field=models.BooleanField(default=False, help_text='Si un lien vers cette page devra             apparaître dans le bas de page', verbose_name='Faire apparaître dans le bas de page'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_mangmap',
            field=models.BooleanField(default=False, help_text="La première actualité mise en avant sur la             page d'accueil est la dernière actualité mangmap", verbose_name='Est une nouvelle mangmap'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text="Permet de trier l'ordre d'affichage             dans la page des actualités", verbose_name='Date de publication'),
        ),
    ]
