# Generated by Django 3.2.16 on 2023-01-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangmap', '0017_auto_20230103_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='key_figures_introduction',
        ),
    ]
