# Generated by Django 3.2.11 on 2022-01-31 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('main', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('country', models.CharField(choices=[('Afrique du Sud', 'Afrique du Sud'), ('Algérie', 'Algérie'), ('Angola', 'Angola'), ('Bénin', 'Bénin'), ('Botswana', 'Botswana'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cameroun', 'Cameroun'), ('Cap-Vert', 'Cap-Vert'), ('République centrafricaine', 'République centrafricaine'), ('Comores', 'Comores'), ('République du Congo', 'République du Congo'), ('République démocratique du Congo', 'République démocratique du Congo'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Djibouti', 'Djibouti'), ('Égypte', 'Égypte'), ('Érythrée', 'Érythrée'), ('Swaziland', 'Eswatini'), ('Éthiopie', 'Éthiopie'), ('Gabon', 'Gabon'), ('Gambie', 'Gambie'), ('Ghana', 'Ghana'), ('Guinée', 'Guinée'), ('Guinée-Bissau', 'Guinée-Bissau'), ('Guinée équatoriale', 'Guinée équatoriale'), ('Kenya', 'Kenya'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libye', 'Libye'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Maroc', 'Maroc'), ('Maurice', 'Maurice'), ('Mauritanie', 'Mauritanie'), ('Mozambique', 'Mozambique'), ('Namibie', 'Namibie'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Ouganda', 'Ouganda'), ('Rwanda', 'Rwanda'), ('São Tomé-et-Principe', 'São Tomé-et-Principe'), ('Sénégal', 'Sénégal'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Somalie', 'Somalie'), ('Soudan', 'Soudan'), ('Soudan du Sud', 'Soudan du Sud'), ('Tanzanie', 'Tanzanie'), ('Tchad', 'Tchad'), ('Togo', 'Togo'), ('Tunisie', 'Tunisie'), ('Zambie', 'Zambie'), ('Zimbabwe', 'Zimbabwe')], max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
