# Generated by Django 3.2.11 on 2022-03-18 15:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("main", "0005_auto_20220318_1344"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.core.blocks.CharBlock(
                                    form_classname="full title",
                                    label="Titre de la page",
                                ),
                            ),
                            (
                                "section",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("blue", "Bleue"),
                                                    ("pink", "Rose"),
                                                    ("white", "Blanche"),
                                                    ("none", "Sans couleur"),
                                                ],
                                                help_text="Couleur de fond",
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image à côté du paragraphe",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "position",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("right", "Droite"),
                                                    ("left", "Gauche"),
                                                ],
                                                help_text="Position de l'image",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "link",
                                                    "h3",
                                                    "h4",
                                                    "ol",
                                                    "ul",
                                                    "h2",
                                                ],
                                                label="Contenu",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "sub_section",
                                            wagtail.core.blocks.ListBlock(
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "color",
                                                            wagtail.core.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("blue", "Bleue"),
                                                                    ("pink", "Rose"),
                                                                    (
                                                                        "white",
                                                                        "Blanche",
                                                                    ),
                                                                    (
                                                                        "none",
                                                                        "Sans couleur",
                                                                    ),
                                                                ],
                                                                help_text="Couleur de fond",
                                                            ),
                                                        ),
                                                        (
                                                            "paragraph",
                                                            wagtail.core.blocks.RichTextBlock(
                                                                features=[
                                                                    "bold",
                                                                    "italic",
                                                                    "link",
                                                                    "h3",
                                                                    "h4",
                                                                    "ol",
                                                                    "ul",
                                                                ],
                                                                label="Contenu",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "columns",
                                                            wagtail.core.blocks.ListBlock(
                                                                wagtail.core.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "color",
                                                                            wagtail.core.blocks.ChoiceBlock(
                                                                                choices=[
                                                                                    (
                                                                                        "blue",
                                                                                        "Bleue",
                                                                                    ),
                                                                                    (
                                                                                        "pink",
                                                                                        "Rose",
                                                                                    ),
                                                                                    (
                                                                                        "white",
                                                                                        "Blanche",
                                                                                    ),
                                                                                    (
                                                                                        "none",
                                                                                        "Sans couleur",
                                                                                    ),
                                                                                ],
                                                                                help_text="Couleur de fond",
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "paragraph",
                                                                            wagtail.core.blocks.RichTextBlock(
                                                                                features=[
                                                                                    "bold",
                                                                                    "italic",
                                                                                    "link",
                                                                                    "h3",
                                                                                    "h4",
                                                                                    "ol",
                                                                                    "ul",
                                                                                ],
                                                                                label="Contenu",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                    ],
                                                                    label="Colonne",
                                                                ),
                                                                label="Colonnes",
                                                            ),
                                                        ),
                                                    ],
                                                    label="Sous section",
                                                ),
                                                label="Sous sections",
                                            ),
                                        ),
                                    ],
                                    label="Section",
                                ),
                            ),
                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ("pdf", wagtail.documents.blocks.DocumentChooserBlock()),
                        ],
                        blank=True,
                        help_text="Corps de la page",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page de contenu",
                "verbose_name_plural": "Pages de contenu",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.AlterModelOptions(
            name="newslistpage",
            options={
                "verbose_name": "Page des actualités",
                "verbose_name_plural": "Pages des actualités",
            },
        ),
        migrations.AlterModelOptions(
            name="ressourcespage",
            options={
                "verbose_name": "Page des ressources",
                "verbose_name_plural": "Pages des ressources",
            },
        ),
        migrations.AlterField(
            model_name="homepage",
            name="introduction",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                null=True,
                verbose_name="Introduction du bloc des ressources",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="news_block_title",
            field=models.CharField(
                blank=True,
                default="Dernières actualités",
                max_length=64,
                verbose_name="Titre du bloc des actualités",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="ressources_block_explication",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                help_text="Explication présente sous les listes des différents profils",
                null=True,
                verbose_name="Explication du bloc des ressources",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="ressources_block_introduction",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                null=True,
                verbose_name="Introduction du bloc des ressources",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="ressources_block_title",
            field=models.CharField(
                blank=True,
                default="Des ressources adaptées à votre profil",
                max_length=64,
                verbose_name="Titre du bloc des ressources",
            ),
        ),
    ]
