# Generated by Django 3.2.11 on 2022-03-30 14:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_auto_20220318_1552"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="icon",
        ),
        migrations.AlterField(
            model_name="homepage",
            name="introduction",
            field=wagtail.core.fields.RichTextField(
                blank=True, null=True, verbose_name="Introduction"
            ),
        ),
    ]
