# Generated by Django 3.2.11 on 2022-04-04 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailcore", "0066_collection_management_permissions"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0007_auto_20220330_1452"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ressource",
            new_name="Resource",
        ),
        migrations.RenameModel(
            old_name="RessourcesPage",
            new_name="ResourcesPage",
        ),
    ]
