# Generated by Django 3.2.11 on 2022-04-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_resource_resource_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(
                        max_length=20, verbose_name="code (ne pas changer !)"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("data", "Donnée"),
                    ("training", "Support de formation"),
                    ("product", "Produit thématique"),
                ],
                default="data",
                max_length=20,
                verbose_name="Type de ressource",
            ),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, verbose_name="code à deux lettres"),
                ),
                (
                    "latitude",
                    models.CharField(max_length=20, verbose_name="latitude du centre"),
                ),
                (
                    "longitude",
                    models.CharField(max_length=20, verbose_name="longitude du centre"),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.worldzone",
                    ),
                ),
            ],
        ),
    ]
