# Generated by Django 3.2.11 on 2022-04-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_auto_20220409_0920"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "pays", "verbose_name_plural": "pays"},
        ),
        migrations.AlterModelOptions(
            name="worldzone",
            options={
                "verbose_name": "zone du monde",
                "verbose_name_plural": "zones du monde",
            },
        ),
    ]
