# Generated by Django 3.2.11 on 2022-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_auto_20220409_1811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="latitude",
            field=models.FloatField(verbose_name="latitude du centre"),
        ),
        migrations.AlterField(
            model_name="country",
            name="longitude",
            field=models.FloatField(verbose_name="longitude du centre"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="countries",
            field=models.ManyToManyField(
                blank=True, to="main.Country", verbose_name="Pays"
            ),
        ),
    ]
