# Generated by Django 3.2.11 on 2022-04-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_auto_20220410_1133"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "Type de ressource",
                "verbose_name_plural": "Types de ressource",
            },
        ),
        migrations.RemoveField(
            model_name="resource",
            name="resource_type",
        ),
        migrations.AddField(
            model_name="resource",
            name="types",
            field=models.ManyToManyField(blank=True, to="main.ResourceType"),
        ),
    ]
