# Generated by Django 3.2.11 on 2022-04-12 08:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("main", "0018_auto_20220412_0854"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "left_column",
                    wagtail.core.fields.RichTextField(verbose_name="colonne de gauche"),
                ),
                (
                    "newsletter_text",
                    wagtail.core.fields.RichTextField(
                        verbose_name="texte d'introduction newsletter"
                    ),
                ),
            ],
            options={
                "verbose_name": "Page de contact",
            },
            bases=("wagtailcore.page",),
        ),
    ]
