# Generated by Django 3.2.11 on 2022-04-13 11:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=40)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='main_thematic',
            field=models.ForeignKey(blank=True, help_text="ce champ n'est utilisé que lorsque plusieurs thématiques sont sélectionnées", null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.thematic', verbose_name='Thématique principale'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, unique=True, verbose_name="Slug (URL de l'actualité)"),
        ),
        migrations.AlterField(
            model_name='resource',
            name='short_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, unique=True, verbose_name='Slug (URL de la ressource)'),
        ),
    ]
