# Generated by Django 3.2.11 on 2022-04-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220413_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_geodev',
            field=models.BooleanField(default=False, help_text="La première actualité mise en avant sur la page d'accueil est la dernière actualité GeoDEV", verbose_name='Est une nouvelle GeoDEV'),
        ),
    ]
