# Generated by Django 3.2.11 on 2022-04-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20220421_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualitytype',
            options={'ordering': ('name',), 'verbose_name': "Type d'actualité", 'verbose_name_plural': "Types d'actualité"},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'ordering': ('name',), 'verbose_name': 'Type de ressource', 'verbose_name_plural': 'Types de ressource'},
        ),
        migrations.AddField(
            model_name='news',
            name='countries',
            field=models.ManyToManyField(help_text="Ce champ n'est pas encore utilisé", to='main.Country', verbose_name='Pays liés'),
        ),
        migrations.AddField(
            model_name='news',
            name='zones',
            field=models.ManyToManyField(help_text="Ce champ n'est pas encore utilisé", to='main.WorldZone', verbose_name='Zones du monde liées'),
        ),
    ]
