# Generated by Django 3.2.11 on 2022-04-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220422_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news',
            field=models.ManyToManyField(blank=True, related_name='_main_news_news_+', to='main.News', verbose_name='Actualités liées'),
        ),
        migrations.AddField(
            model_name='news',
            name='resources',
            field=models.ManyToManyField(blank=True, to='main.Resource', verbose_name='Ressources liées'),
        ),
        migrations.AddField(
            model_name='news',
            name='thematics',
            field=models.ManyToManyField(help_text="Ce champ n'est pas encore utilisé", to='main.Thematic', verbose_name='Thématiques liées'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='ressources', to='main.Profile', verbose_name='Profils'),
        ),
    ]
