# Generated by Django 3.2.11 on 2022-04-22 13:51

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20220422_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Concerne tous les pays'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Titre de la page')), ('section', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'h2'], label='Contenu', required=True)), ('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image à côté du paragraphe', required=False)), ('position', wagtail.core.blocks.ChoiceBlock(choices=[('right', 'Droite'), ('left', 'Gauche')], help_text="Position de l'image", required=False)), ('sub_section', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul'], label='Contenu', required=False)), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul'], label='Contenu', required=False))], label='Colonne'), label='Colonnes'))], label='Sous section'), default=[], label='Sous sections'))], label='Section')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text='Corps de la page', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Titre de la page')), ('section', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'h2'], label='Contenu', required=True)), ('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image à côté du paragraphe', required=False)), ('position', wagtail.core.blocks.ChoiceBlock(choices=[('right', 'Droite'), ('left', 'Gauche')], help_text="Position de l'image", required=False)), ('sub_section', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul'], label='Contenu', required=False)), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul'], label='Contenu', required=False))], label='Colonne'), label='Colonnes'))], label='Sous section'), default=[], label='Sous sections'))], label='Section')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text='Corps de la page', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Titre de la page')), ('section', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'h2'], label='Contenu', required=True)), ('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image à côté du paragraphe', required=False)), ('position', wagtail.core.blocks.ChoiceBlock(choices=[('right', 'Droite'), ('left', 'Gauche')], help_text="Position de l'image", required=False)), ('sub_section', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul'], label='Contenu', required=False)), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul'], label='Contenu', required=False))], label='Colonne'), label='Colonnes'))], label='Sous section'), default=[], label='Sous sections'))], label='Section')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text='Corps de la page', verbose_name='Contenu'),
        ),
    ]
