# Generated by Django 3.2.13 on 2022-06-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20220422_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news',
        ),
    ]
