# Generated by Django 3.2.13 on 2022-08-31 08:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_news_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='resources_block_introduction',
        ),
        migrations.AlterField(
            model_name='resource',
            name='short_description',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Description courte'),
        ),
    ]
