# Generated by Django 3.2.13 on 2022-11-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20221103_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Concerne tous les pays'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='source_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lien vers la Ressource (URL)'),
        ),
    ]
