# Generated by Django 3.2.13 on 2022-11-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20221104_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='zones',
            field=models.ManyToManyField(blank=True, to='main.WorldZone', verbose_name='Zones'),
        ),
    ]
